### PR TITLE
Various Tweaks & Corrections

### PR DESCRIPTION
**Pull request by kingthorin**
- Add jemoji plugin so that markdown emoji used on the overview tab render properly. 
- Exclude project source code directories from web deployment.
- Remove duplicate and wrong project classification details. 
- Linkify URLs on the user guide tab.
- Remove spurious comma in heading on main page.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
The checkmark doesn't show up very well, but at least they work now instead of showing plaintext:
Before:
image

After:
image

Before:
image

After:
image

**Review by azharanees — APPROVED** [review]

**Comment by kingthorin** [comment]
@azharanees thanks for the approval, what’s the merge plan?

**Comment by azharanees** [comment]
> @azharanees thanks for the approval, what’s the merge plan?

Once @aramrami has approved we can merge it

**Comment by aramrami** [comment]
Ok for me Aazhar. You can merge it.

**Pull request merged**
